# Generated by Django 3.0.6 on 2020-05-18 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20200518_2351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
